# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Cypress
      uses: cypress-io/github-action@v1.16.1
      working-directory: apps/ide-ui-e2e 
    - uses: actions/upload-artifact@v1
      working-directory: apps/ide-ui-e2e 
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v1
      working-directory: apps/ide-ui-e2e 
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos
